version: '3'
services:
  ota_backend:
    build:
      context: .
    image: ota_server:latest
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      SERVER_HOST: ${SERVER_HOST}
      LOGGING_LEVEL: ${LOGGING_LEVEL}
    volumes:
      - ./docker/firmwares:/firmwares
    logging:
      options:
        max-size: '10m'
        max-file: '5'

  ota_nginx:
    build:
      context: docker/nginx
    image: ota_nginx:latest
    restart: unless-stopped
    ports:
    - 80:80
    - 443:443
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx

      SERVER_HOST: ${SERVER_HOST}
      OTA_USERNAME: ${OTA_USERNAME}
      OTA_PASSWORD: ${OTA_PASSWORD}
    volumes:
      - ./docker/nginx/nginx-ssl.conf:/etc/nginx/templates/nginx.conf.template
      - ./docker/nginx/set_up_users.sh:/docker-entrypoint.d/set_up_users.sh
      - ./docker/nginx/gen_dhparam.sh:/docker-entrypoint.d/gen_dhparam.sh
      - ./docker/nginx/ssl/${SERVER_CERT_FILE}:/etc/ssl/certs/ota_server.crt
      - ./docker/nginx/ssl/${SERVER_KEY_FILE}:/etc/ssl/private/ota_server.key
    depends_on:
      - ota_backend
    logging:
      options:
        max-size: '10m'
        max-file: '5'
