FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive
RUN sed --in-place --regexp-extended "s/(\/\/)(archive\.ubuntu)/\1hu.\2/" /etc/apt/sources.list && \
	apt-get update && \
	apt-get dist-upgrade -y
	
RUN apt-get install -y python3 jq nginx nano vim openssl apache2-utils inotify-tools -y


RUN mkdir -p /ota/config
RUN mkdir ota/scripts
RUN mkdir -p /var/www/html/fw/

COPY files/nginx.conf /etc/nginx/nginx.conf
COPY files/conf.json /ota/config/conf.json
COPY files/manifest.py /ota/scripts/manifest.py

RUN sed -i "s/__HOST_NAME__/$(jq -r '.server_ip' /ota/config/conf.json)/g" /etc/nginx/nginx.conf
RUN sed -i "s/__SERVICE_NAME__/$(jq -r '.server_name' /ota/config/conf.json)/g" /etc/nginx/nginx.conf

RUN mkdir -p /etc/ssl/certs/
RUN mkdir -p /etc/ssl/private/

COPY files/entrypoint.sh  /ota/scripts/entrypoint.sh
RUN chmod 0755 /ota/scripts/entrypoint.sh

COPY files/signed_cert_gen.sh  /ota/scripts/signed_cert_gen.sh
RUN chmod 0755 /ota/scripts/signed_cert_gen.sh

COPY files/regen.sh  /ota/scripts/regen.sh
RUN chmod 0755 /ota/scripts/regen.sh

COPY files/set_up_users.sh  /ota/scripts/set_up_users.sh
RUN chmod 0755 /ota/scripts/set_up_users.sh

EXPOSE 80 443

ENTRYPOINT /ota/scripts/entrypoint.sh
